name: 'Artifact Java local tests'
description: 'Runs java local tests on the Dagger LOCAL-SNAPSHOT artifacts.'

runs:
  using: "composite"
  steps:
    - name: 'Check out repository'
      uses: actions/checkout@v4
    - name: 'Cache Gradle files'
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-java-${{ env.USE_JAVA_VERSION_FOR_GRADLE }}-kotlin-${{ env.USE_KOTLIN_VERSION }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-java-${{ env.USE_JAVA_VERSION_FOR_GRADLE }}-kotlin-${{ env.USE_KOTLIN_VERSION }}-
          ${{ runner.os }}-gradle-java-${{ env.USE_JAVA_VERSION_FOR_GRADLE }}-
          ${{ runner.os }}-gradle-
    - name: 'Download local snapshot for tests'
      uses: actions/download-artifact@v4
      with:
        name: local-snapshot
        path: ~/.m2/repository/com/google/dagger
    - name: 'Gradle Java local tests (Java ${{ env.USE_JAVA_VERSION_FOR_GRADLE }}, Kotlin ${{ env.USE_KOTLIN_VERSION }})'
      run: ./util/run-local-gradle-tests.sh "${{ env.USE_JAVA_VERSION_FOR_GRADLE }}" "${{ env.USE_KOTLIN_VERSION }}" "${{ env.USE_KSP_VERSION }}"
      shell: bash
    - name: 'Upload test reports (Java ${{ env.USE_JAVA_VERSION_FOR_GRADLE }}, Kotlin ${{ env.USE_KOTLIN_VERSION }})'
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: java-tests-reports-java-${{ env.USE_JAVA_VERSION_FOR_GRADLE }}-kotlin-${{ env.USE_KOTLIN_VERSION }}
        path: ${{ github.workspace }}/**/build/reports/tests/*
